SELECT ap.TIME, 'P' AS type, mo.name,mo.health_id,ap.ID
FROM MIDWIFE m,ASSIGNMENT a,APPOINTMENTs ap, MOTHER mo
WHERE m.id='8335' AND ap.DATE='2020-09-02' AND m.id=a.primaryMF AND a.assignid=ap.assignid AND (a.motherhealthid=mo.health_id)
UNION
SELECT ap.TIME,'B' AS type, mo.name,mo.health_id,ap.ID
FROM MIDWIFE m,ASSIGNMENT a,APPOINTMENTs ap, MOTHER mo
WHERE m.id='8335' AND ap.DATE='2020-09-02' AND m.id=a.BACKMF AND a.assignid=ap.assignid AND (a.motherhealthid=mo.health_id)
ORDER BY TIME
;

SELECT n.DATE,TIMESTAMP,CONTENT
FROM NOTE n, MOTHER m, ASSIGNMENT a, APPOINTMENTS ap
WHERE m.HEALTH_ID='294969047'AND a.MOTHERHEALTHID=m.HEALTH_ID AND a.ASSIGNID=ap.ASSIGNID AND ap.ID=n.APPID
ORDER BY DATE DESC ,TIMESTAMP DESC
;

SELECT PREDATE,TYPE,RESULT
FROM TEST t,APPLYTESTON a
WHERE a.MOTHERHEALTHID='294969047' AND a.TESTID=t.ID
ORDER BY PREDATE DESC
;

UPDATE NOTE
SET CONTENT= 'YESYESYES'
WHERE NOTE.APPID=''
;

SELECT ID
FROM APPOINTMENTS ap,ASSIGNMENT a
WHERE a.MOTHERHEALTHID='294969047' AND ap.TIME='12:00:00' AND a.ASSIGNID=ap.ASSIGNID
;

SELECT m.health_id
FROM ASSIGNMENT a,APPOINTMENTs ap, MOTHER m
WHERE a.motherhealthid=m.health_id AND a.assignid=ap.assignid AND ap.ID= '1249'
;

INSERT INTO Note (appID, TimeStamp, Date, content)
VALUES
    (1249,'12:00:00','2020-09-02','Babies are great.')
;

DELETE FROM NOTE
WHERE APPID=1249 AND TIMESTAMP='00:35:07';

SELECT MOTHERHEALTHID,EXPTIMEFRAME
FROM ASSIGNMENT a,APPOINTMENTS ap
WHERE a.ASSIGNID=ap.ASSIGNID AND ap.ID='1249'
;
DELETE FROM APPLYTESTON WHERE TESTID='3619';
DELETE FROM TEST WHERE PREDATE='2022-03-16';

SELECT MOTHERHEALTHID
FROM PREGNANCY
GROUP BY MOTHERHEALTHID
HAVING COUNT(*)>=2
;

INSERT INTO Appointments (ID, Time, Date, AssignID)
VALUES
(2588,'13:45:00','2020-09-02',5658);

SELECT n.APPID,n.DATE,n.TIMESTAMP,n.CONTENT,m.HEALTH_ID AS MOTHER_id,f.ID AS FATHER_id,p.NUMOFTIMES
FROM MOTHER m, FATHER f,PREGNANCY p,APPOINTMENTS a,NOTE n, ASSIGNMENT a2
WHERE n.APPID=a.ID AND a.ASSIGNID=a2.ASSIGNID AND (a2.MOTHERHEALTHID=m.HEALTH_ID AND a2.EXPTIMEFRAME=p.EXPTIMEFRAME)AND
      m.HEALTH_ID='294969047' AND m.HEALTH_ID=p.MOTHERHEALTHID AND f.ID=p.FATHERID
ORDER BY n.DATE DESC,n.TIMESTAMP DESC
;


SELECT t.PREDATE,t.TYPE,t.RESULT,m.HEALTH_ID AS MOTHER_id,f.ID AS FATHER_id,p.NUMOFTIMES
FROM  MOTHER m, FATHER f,PREGNANCY p, TEST t, APPLYTESTON a
WHERE (a.EXPTIMEFRAME= p.EXPTIMEFRAME AND a.MOTHERHEALTHID=p.MOTHERHEALTHID) AND a.TESTID=t.ID AND p.MOTHERHEALTHID=m.HEALTH_ID AND p.FATHERID=f.ID
AND m.HEALTH_ID='294969047'
ORDER BY t.PREDATE DESC
;

SELECT t.PREDATE,t.TYPE,t.RESULT,m.HEALTH_ID AS MOTHER_id,f.ID AS FATHER_id,p.NUMOFTIMES
FROM  MOTHER m, FATHER f,PREGNANCY p, TEST t, APPLYTESTON a
WHERE (a.EXPTIMEFRAME= p.EXPTIMEFRAME AND a.MOTHERHEALTHID=p.MOTHERHEALTHID) AND a.TESTID=t.ID AND p.MOTHERHEALTHID=m.HEALTH_ID AND p.FATHERID=f.ID
  AND m.HEALTH_ID='41584645'
ORDER BY t.PREDATE DESC
;

SELECT MONTH(BIRTHDATE) AS month, COUNT(*) AS numofbirth FROM BABIES WHERE MONTH(BIRTHDATE)='1' OR MONTH(BIRTHDATE)='2' OR MONTH(BIRTHDATE)='3' OR MONTH(BIRTHDATE)='4' OR MONTH(BIRTHDATE)='5' OR MONTH(BIRTHDATE)='6'OR MONTH(BIRTHDATE)='7' OR MONTH(BIRTHDATE)='8' OR MONTH(BIRTHDATE)='9' OR MONTH(BIRTHDATE)='10' OR MONTH(BIRTHDATE)='11' OR MONTH(BIRTHDATE)='12' group by MONTH(BIRTHDATE) HAVING COUNT(*)>0 ;